import React from 'react';
import { Link } from 'react-router-dom';
import { ShieldCheck, Lock, Eye, KeyRound, Building, CheckCircle2 } from 'lucide-react';
import { useApp } from '../context/AppContext';

export const PrivacyPolicyPage: React.FC = () => {
  const { darkMode } = useApp();

  return (
    <div className={`min-h-screen py-8 transition-colors duration-200 ${
      darkMode ? 'bg-slate-900 text-slate-100' : 'bg-[#F4F7FB] text-slate-800'
    }`}>
      <div className="max-w-4xl mx-auto px-4 sm:px-6">
        
        {/* Breadcrumb */}
        <div className="flex items-center space-x-2 text-xs text-slate-500 dark:text-slate-400 mb-6">
          <Link to="/" className="hover:text-[#0056D2] font-semibold">Home</Link>
          <span>/</span>
          <span className="text-[#0056D2] font-bold">Privacy Policy & Data Security</span>
        </div>

        {/* Header Card */}
        <div className={`rounded-3xl p-6 sm:p-8 border shadow-md mb-8 ${
          darkMode ? 'bg-slate-800 border-slate-700' : 'bg-white border-slate-200/80'
        }`}>
          <div className="flex items-center space-x-3.5">
            <div className="w-12 h-12 rounded-2xl bg-emerald-100 dark:bg-emerald-950 text-emerald-600 dark:text-emerald-400 flex items-center justify-center flex-shrink-0">
              <Lock className="w-6 h-6" />
            </div>
            <div>
              <h1 className="text-xl sm:text-2xl font-black tracking-tight leading-snug">
                National Privacy Policy & Data Protection
              </h1>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
                Information Technology Act 2000, Digital Personal Data Protection (DPDP) Act 2023, and UIDAI Aadhaar Regulations.
              </p>
            </div>
          </div>
        </div>

        {/* Content Card */}
        <div className={`rounded-3xl p-6 sm:p-8 border shadow-xl space-y-6 text-xs text-slate-700 dark:text-slate-300 leading-relaxed ${
          darkMode ? 'bg-slate-800 border-slate-700' : 'bg-white border-slate-200/80'
        }`}>
          <div>
            <h2 className="text-sm font-extrabold text-slate-900 dark:text-white mb-2 flex items-center gap-2">
              <ShieldCheck className="w-4 h-4 text-emerald-600" />
              <span>1. Aadhaar e-KYC Data Privacy & Encryption</span>
            </h2>
            <p>
              Parivahan Sarathi performs Aadhaar authentication in accordance with Section 8 of the Aadhaar (Targeted Delivery of Financial and Other Subsidies, Benefits and Services) Act, 2016. Citizen demographic data is transmitted over secure 256-bit TLS encrypted channels and raw biometric data is never stored locally on portal databases.
            </p>
          </div>

          <div>
            <h2 className="text-sm font-extrabold text-slate-900 dark:text-white mb-2 flex items-center gap-2">
              <Lock className="w-4 h-4 text-blue-600" />
              <span>2. Purpose-Bound Collection & Non-Disclosure</span>
            </h2>
            <p>
              Information collected (Name, Father's Name, Date of Birth, Address, Blood Group, Mobile Number) is used exclusively for the statutory purpose of issuing Driving Licences, Conductor Licences, and maintaining the National Register under Chapter II of the Motor Vehicles Act 1988. No personal identity data is sold or shared with commercial entities.
            </p>
          </div>

          <div>
            <h2 className="text-sm font-extrabold text-slate-900 dark:text-white mb-2 flex items-center gap-2">
              <KeyRound className="w-4 h-4 text-purple-600" />
              <span>3. DigiLocker National Vault Integration</span>
            </h2>
            <p>
              Digital Driving Licences generated by this portal are cryptographically signed by National Informatics Centre (NIC) and automatically synchronized with the citizen's official DigiLocker account under Rule 9A of the Information Technology (Preservation and Retention of Information by Intermediaries) Rules 2016.
            </p>
          </div>

          <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-900 border dark:border-slate-700 space-y-2">
            <span className="font-bold text-slate-900 dark:text-white">Chief Information Security Officer (CISO)</span>
            <p className="text-[11px] text-slate-500">Ministry of Road Transport and Highways, Transport Bhawan, 1 Parliament Street, New Delhi - 110001. Email: ciso-morth@nic.in</p>
          </div>
        </div>

      </div>
    </div>
  );
};
